{% set name = "GWFrames" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # we have to use git_url here to get the submodules needed for the
  # build; see <https://github.com/conda-forge/xgboost-feedstock/issues/22>
  git_url: https://github.com/moble/{{ name }}.git
  git_rev: {{ version }}
  # Mitigate the above by just shallow cloning, while still capturing the tag
  git_depth: 10

build:
  number: 3
  script: "cd Code && {{ PYTHON }} setup.py install"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - fftw
    - gsl
    - hdf5
    - numpy
    - swig =3.0.10
    - libopenblas  # [linux]
    - libstdcxx-ng  # [linux]
    - libgcc-ng  # [linux]

  run:
    - python
    - fftw
    - gsl
    - hdf5
    - {{ pin_compatible('numpy') }}
    - h5py
    - scipy
    - matplotlib-base

test:
  imports:
    - GWFrames

about:
  home: https://github.com/moble/GWFrames
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create and manipulate gravitational waveforms
  dev_url: https://github.com/moble/GWFrames

extra:
  recipe-maintainers:
    - moble
